# SSL Config
server.ssl.key-store = file:/etc/openelis-global/keystore
server.ssl.key-store-password = kspass
server.ssl.key-password = kspass
server.ssl.trust-store= file:/etc/openelis-global/truststore
server.ssl.trust-store-password=tspass
encryption.general.password=kspass

# Co-resident FHIR Server
org.openelisglobal.fhirstore.uri=https://fhir.openelis.org:8443/fhir/
org.openelisglobal.fhirstore.username=admin
org.openelisglobal.fhirstore.password=adminADMIN!
org.openelisglobal.fhir.subscriber.allowHTTP=true

# Remote FHIR server/Consolidated Server
org.openelisglobal.remote.source.uri=
org.openelisglobal.remote.source.updateStatus=true
org.openelisglobal.remote.source.identifier=Practitioner/*
org.openelisglobal.remote.poll.frequency=120000
org.openelisglobal.task.useBasedOn=true

org.openelisglobal.fhir.subscriber=
org.openelisglobal.fhir.subscriber.resources=Task,Patient,ServiceRequest,DiagnosticReport,Observation,Specimen,Practitioner,Encounter

# Odoo Integration (disabled)
org.openelisglobal.odoo.enabled=false
org.openelisglobal.odoo.map.testname.locale=en
org.openelisglobal.odoo.baseUrl=
org.openelisglobal.odoo.database=
org.openelisglobal.odoo.username=
org.openelisglobal.odoo.password=

# Paging
org.openelisglobal.paging.patients.pageSize=99
org.openelisglobal.paging.results.pageSize=99
org.openelisglobal.paging.validation.pageSize=99
org.openelisglobal.paging.displaylist.pageSize=99

# SAML (disabled)
org.itech.login.saml=false

# Facility Details
org.openelisglobal.facility.country=US
org.openelisglobal.facility.state=WA
org.openelisglobal.facility.district=King
org.openelisglobal.facility.city=Seattle
org.openelisglobal.facility.postalcode=98195
org.openelisglobal.facility.id=OpenELIS-Test-Lab

# Mail (disabled for testing)
org.openelisglobal.mail.bcc=
org.openelisglobal.mail.from=

# Notification (disabled)
org.openelisglobal.notification.bmp.provider=TWILIO
org.openelisglobal.notification.twilio.from=

# Freezer monitoring (disabled)
org.openelisglobal.freezermonitoring.enabled=false

# Help URLs
org.openelisglobal.help.manual.url=https://uwdigi.atlassian.net/wiki/spaces/OG/folder/261455874
org.openelisglobal.help.tutorials.url=https://video.openelis-global.org
org.openelisglobal.help.release-notes.url=https://roadmap.openelis-global.org

# Configuration
org.openelisglobal.configuration.autocreate=true
org.openelisglobal.configuration.dir=/var/lib/openelis-global/configuration/backend
org.openelisglobal.program.autocreate=true
org.openelisglobal.menu.configuration.autocreate=false
