# ASM3 configuration for gym_anything environment

base_url = http://localhost:8080
service_url = http://localhost:8080/service
locale = en
timezone = 0
log_location = stderr
log_debug = true

# Database info
db_type = POSTGRESQL
db_host = localhost
db_port = 5432
db_username = asm
db_password = asm
db_name = asm

db_timeout = 0
deployment_type = wsgi
