[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2_err.log

[program:solr]
command=/opt/solr/bin/solr start -f -force
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/solr.log
stderr_logfile=/var/log/supervisor/solr_err.log

[program:redis]
command=/usr/bin/redis-server --daemonize no
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis_err.log
