#!/bin/sh

export XDG_SESSION_TYPE=x11
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -r "$HOME/.Xresources" ] && xrdb "$HOME/.Xresources"
vncconfig -nowin &
xhost +local: >/dev/null 2>&1 || true
exec dbus-launch --exit-with-session gnome-session
