#!/usr/bin/env python3
"""Provision the QEMU Ubuntu base's userspace inside a Sandweave template."""

import os
from pathlib import Path
import subprocess

from build_base_qcow2_nodocker import CLOUD_INIT_USER_DATA


def main():
    os.environ["DEBIAN_FRONTEND"] = "noninteractive"
    sources = Path("/etc/apt/sources.list")
    sources.write_text(sources.read_text().replace("http://", "https://"))
    # gVisor has no shared kernel keyrings. Apply the systemd setting to the
    # base's services and mounts, including units later generated by snapd.
    for unit_type, section in (("service", "Service"), ("mount", "Mount")):
        directory = Path(f"/etc/systemd/system/{unit_type}.d")
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "sandweave.conf").write_text(f"[{section}]\nKeyringMode=inherit\n")
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["apt-get", "update"], check=True)
    subprocess.run(["apt-get", "install", "-y", "python3-yaml", "squashfuse",
                    "software-properties-common"], check=True)
    # Use the repository's native Firefox package source for the shared desktop.
    # Install the pin before Ubuntu desktop dependencies can select the Snap shim.
    subprocess.run(["add-apt-repository", "-y", "-n", "ppa:mozillateam/ppa"], check=True)
    Path("/etc/apt/preferences.d/mozilla-firefox").write_text(
        "Package: *\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1001\n")
    subprocess.run(["apt-get", "update"], check=True)
    subprocess.run(["apt-get", "install", "-y", "--allow-downgrades", "firefox"], check=True)
    # /tmp lives on the root filesystem so filesystem caches include its files.
    # Preserve those files when systemd initializes a restored filesystem.
    Path("/etc/tmpfiles.d/tmp.conf").write_text("d /tmp 1777 root root -\n")
    import yaml

    config = yaml.safe_load(CLOUD_INIT_USER_DATA)
    # Xvnc supplies the display; Sandweave owns networking, devices and kernel
    # settings. Host network discovery, ACPI and ext4 maintenance do not apply.
    subprocess.run(["systemctl", "mask", "gdm.service", "gdm3.service",
                    "acpid.service", "acpid.socket", "e2scrub_reap.service",
                    "systemd-sysctl.service", "systemd-udevd.service",
                    "systemd-udevd-control.socket", "systemd-udevd-kernel.socket",
                    "NetworkManager.service", "NetworkManager-wait-online.service",
                    "avahi-daemon.service", "avahi-daemon.socket",
                    "rtkit-daemon.service"], check=True)
    subprocess.run(["apt-get", "install", "-y", "--install-recommends",
                    *config["packages"]], check=True)
    for user in config["users"]:
        name = user["name"]
        subprocess.run(["usermod", "-aG", ",".join(user["groups"]),
                        "-s", user["shell"], name], check=True)
        ssh = Path("/home") / name / ".ssh"
        ssh.mkdir(mode=0o700, exist_ok=True)
        keys = ssh / "authorized_keys"
        keys.write_text("\n".join(user["ssh_authorized_keys"]) + "\n")
        keys.chmod(0o600)
        subprocess.run(["chown", "-R", f"{name}:{name}", str(ssh)], check=True)
    subprocess.run(["chpasswd"], input="\n".join(config["chpasswd"]["list"]) + "\n",
                    text=True, check=True)
    for command in config["runcmd"]:
        subprocess.run(["/bin/bash", "-e", "-c", command], check=True)
    # Use Sandweave's VNC/PAM session and its standard user D-Bus. QEMU's
    # xstartup launches a separate bus, which desktop controls cannot reach.
    Path("/home/ga/.vnc/xstartup").unlink()
    # Advertise the same VNC credential that the shared provisioning installs.
    password_file = Path("/etc/sandweave-vnc-password")
    password_file.write_text("password\n")
    password_file.chmod(0o600)
    subprocess.run(["apt-get", "clean"], check=True)


if __name__ == "__main__":
    main()
